# Site settings
title: Pete's Blog
header-img: img/home-bg.jpg
email: kongzhp@gmail.com
description: "I love Momo so much , I miss her all the time"
baseurl: ""
url: "http://kongzhp.github.io"
twitter_username: SBootstrap
github_username:  kongzhp
facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate]
